--
-- PostgreSQL database dump
--

-- Dumped from database version 16.2
-- Dumped by pg_dump version 16.2

-- Started on 2024-06-03 14:19:51

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 216 (class 1259 OID 16400)
-- Name: clients; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.clients (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    document character varying(255),
    email character varying(255),
    name_of_applicant character varying(255),
    names character varying(255) NOT NULL,
    number_order_vendor character varying(255),
    phone character varying(255) NOT NULL,
    phone1 character varying(255),
    phone2 character varying(255),
    type integer NOT NULL
);


ALTER TABLE public.clients OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16399)
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.clients ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.clients_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 16499)
-- Name: evidences; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evidences (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    photo_url character varying(255) NOT NULL,
    order_service_id bigint NOT NULL
);


ALTER TABLE public.evidences OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 16498)
-- Name: evidences_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evidences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evidences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 10000000
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16551)
-- Name: order_services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.order_services (
    id bigint NOT NULL,
    created_at timestamp without time zone NOT NULL,
    duration bigint NOT NULL,
    observations character varying(255) NOT NULL,
    order_service_date timestamp without time zone NOT NULL,
    priority integer NOT NULL,
    orders_id bigint NOT NULL,
    services_id integer NOT NULL,
    technician_id integer NOT NULL,
    status integer NOT NULL
);


ALTER TABLE public.order_services OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 16550)
-- Name: order_services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.order_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16407)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id bigint NOT NULL,
    created_at date NOT NULL,
    observations character varying(255) NOT NULL,
    total_charged bigint,
    client_id bigint NOT NULL,
    status integer NOT NULL,
    updated_at date,
    clients_id bigint
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16475)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 215000020
    CACHE 1
);


--
-- TOC entry 233 (class 1259 OID 16581)
-- Name: orders_old; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_old (
    id bigint NOT NULL,
    create_at date,
    observations character varying(5000),
    status character varying(255),
    total_charged bigint,
    update_at date,
    clients_id bigint
);


ALTER TABLE public.orders_old OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 16588)
-- Name: orders_old_services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_old_services (
    orders_id bigint NOT NULL,
    services_id integer NOT NULL
);


ALTER TABLE public.orders_old_services OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 16630)
-- Name: orders_services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders_services (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    duration bigint,
    observations character varying(255),
    order_service_date timestamp without time zone,
    priority integer,
    status integer,
    orders_id bigint,
    services_id integer,
    technician_id integer
);


ALTER TABLE public.orders_services OWNER TO postgres;

--
-- TOC entry 235 (class 1259 OID 16629)
-- Name: orders_services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders_services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16418)
-- Name: schedules; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schedules (
    id_schedule integer NOT NULL,
    date timestamp without time zone,
    hour character varying(255),
    fk_orders bigint NOT NULL,
    users_id integer
);


ALTER TABLE public.schedules OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16417)
-- Name: schedules_id_schedule_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.schedules ALTER COLUMN id_schedule ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedules_id_schedule_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 16510)
-- Name: service_activities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_activities (
    id bigint NOT NULL,
    activity_date timestamp without time zone,
    created_at timestamp without time zone,
    description character varying(255),
    duration bigint,
    priority integer,
    status integer,
    order_id bigint,
    technician_id integer
);


ALTER TABLE public.service_activities OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 16509)
-- Name: service_activities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_activities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.service_activities_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 16424)
-- Name: services; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.services (
    id integer NOT NULL,
    price bigint NOT NULL,
    services_description character varying(255) NOT NULL,
    services_type integer NOT NULL
);


ALTER TABLE public.services OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16423)
-- Name: services_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.services ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.services_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16432)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role integer NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16431)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 16488)
-- Name: warranties; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.warranties (
    id bigint NOT NULL,
    end_date date NOT NULL,
    start_date date NOT NULL,
    reason character varying(255) NOT NULL,
    order_service_id bigint NOT NULL
);


ALTER TABLE public.warranties OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 16487)
-- Name: warranties_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.warranties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.warranties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    MAXVALUE 10000000000
    CACHE 1
);


--
-- TOC entry 4935 (class 0 OID 16400)
-- Dependencies: 216
-- Data for Name: clients; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.clients (id, address, document, email, name_of_applicant, names, number_order_vendor, phone, phone1, phone2, type) FROM stdin;
1	Cll 16 A #1-40	1006531846	prueba@test.com	Pedro Pérez	Pedro Pérez	1	314349203			1
2	Cll 16 A #1-40	1003531846	prueba@test2.com	Brandon Vargas	Brandon Vargas	1	314342344	\N	\N	0
\.


--
-- TOC entry 4947 (class 0 OID 16499)
-- Dependencies: 228
-- Data for Name: evidences; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evidences (id, created_at, photo_url, order_service_id) FROM stdin;
\.


--
-- TOC entry 4951 (class 0 OID 16551)
-- Dependencies: 232
-- Data for Name: order_services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.order_services (id, created_at, duration, observations, order_service_date, priority, orders_id, services_id, technician_id, status) FROM stdin;
1	2024-05-29 21:34:35.0998	5000	Observation example	2024-05-29 21:34:35.0998	1	1	1	1	1
2	2024-05-31 00:27:17.752854	5000000000	Test observation 1	2024-05-31 00:27:17.752854	1	1	1	1	1
3	2024-05-31 00:29:57.910085	5000000000	Test observation 2	2024-05-31 00:27:17.752854	1	1	1	1	1
4	2024-05-31 00:36:16.98586	5000000000	Test observation 3	2024-05-31 00:27:17.752854	1	1	1	1	1
5	2024-05-31 01:13:14.169661	5000000000	Observation Insert from Orders 1	2024-05-31 00:27:17.752854	1	3	1	1	1
\.


--
-- TOC entry 4936 (class 0 OID 16407)
-- Dependencies: 217
-- Data for Name: orders; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders (id, created_at, observations, total_charged, client_id, status, updated_at, clients_id) FROM stdin;
1	2024-05-29	Pruebas de observaciones	1000	1	1	\N	\N
3	2024-05-31	Test Observations 1	\N	1	1	\N	\N
\.


--
-- TOC entry 4952 (class 0 OID 16581)
-- Dependencies: 233
-- Data for Name: orders_old; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_old (id, create_at, observations, status, total_charged, update_at, clients_id) FROM stdin;
\.


--
-- TOC entry 4953 (class 0 OID 16588)
-- Dependencies: 234
-- Data for Name: orders_old_services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_old_services (orders_id, services_id) FROM stdin;
\.


--
-- TOC entry 4955 (class 0 OID 16630)
-- Dependencies: 236
-- Data for Name: orders_services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.orders_services (id, created_at, duration, observations, order_service_date, priority, status, orders_id, services_id, technician_id) FROM stdin;
1	2024-05-30 23:52:33.328252	5000000000	Test observation	2024-05-30 23:52:33.328252	1	1	1	1	2
\.


--
-- TOC entry 4938 (class 0 OID 16418)
-- Dependencies: 219
-- Data for Name: schedules; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.schedules (id_schedule, date, hour, fk_orders, users_id) FROM stdin;
\.


--
-- TOC entry 4949 (class 0 OID 16510)
-- Dependencies: 230
-- Data for Name: service_activities; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_activities (id, activity_date, created_at, description, duration, priority, status, order_id, technician_id) FROM stdin;
\.


--
-- TOC entry 4940 (class 0 OID 16424)
-- Dependencies: 221
-- Data for Name: services; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.services (id, price, services_description, services_type) FROM stdin;
1	1000	Mantenimiento de cocina	1
\.


--
-- TOC entry 4942 (class 0 OID 16432)
-- Dependencies: 223
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, name, password, role) FROM stdin;
2	andres@test1.com	Andrés Test 1	$2a$10$PcAmo6YpCVehlntAWoo/L.23FBAwpSXPXEiAAdOO5vDM3w6SfggRG	1
1	andres.vpineros@gmail.com	Andrés Piñeros	$2a$10$PcAmo6YpCVehlntAWoo/L.23FBAwpSXPXEiAAdOO5vDM3w6SfggRG	1
\.


--
-- TOC entry 4945 (class 0 OID 16488)
-- Dependencies: 226
-- Data for Name: warranties; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.warranties (id, end_date, start_date, reason, order_service_id) FROM stdin;
\.


--
-- TOC entry 4961 (class 0 OID 0)
-- Dependencies: 215
-- Name: clients_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.clients_id_seq', 1, true);


--
-- TOC entry 4962 (class 0 OID 0)
-- Dependencies: 227
-- Name: evidences_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evidences_id_seq', 1, false);


--
-- TOC entry 4963 (class 0 OID 0)
-- Dependencies: 231
-- Name: order_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.order_services_id_seq', 5, true);


--
-- TOC entry 4964 (class 0 OID 0)
-- Dependencies: 224
-- Name: orders_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_id_seq', 3, true);


--
-- TOC entry 4965 (class 0 OID 0)
-- Dependencies: 235
-- Name: orders_services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.orders_services_id_seq', 1, true);


--
-- TOC entry 4966 (class 0 OID 0)
-- Dependencies: 218
-- Name: schedules_id_schedule_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.schedules_id_schedule_seq', 1, false);


--
-- TOC entry 4967 (class 0 OID 0)
-- Dependencies: 229
-- Name: service_activities_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.service_activities_id_seq', 1, false);


--
-- TOC entry 4968 (class 0 OID 0)
-- Dependencies: 220
-- Name: services_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.services_id_seq', 1, true);


--
-- TOC entry 4969 (class 0 OID 0)
-- Dependencies: 222
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- TOC entry 4970 (class 0 OID 0)
-- Dependencies: 225
-- Name: warranties_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.warranties_id_seq', 1, false);


--
-- TOC entry 4742 (class 2606 OID 16536)
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- TOC entry 4760 (class 2606 OID 16503)
-- Name: evidences evidences_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evidences
    ADD CONSTRAINT evidences_pkey PRIMARY KEY (id);


--
-- TOC entry 4764 (class 2606 OID 16555)
-- Name: order_services order_services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_services
    ADD CONSTRAINT order_services_pkey PRIMARY KEY (id);


--
-- TOC entry 4766 (class 2606 OID 16587)
-- Name: orders_old orders_old_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_old
    ADD CONSTRAINT orders_old_pkey PRIMARY KEY (id);


--
-- TOC entry 4748 (class 2606 OID 16413)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 4770 (class 2606 OID 16634)
-- Name: orders_services orders_services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_services
    ADD CONSTRAINT orders_services_pkey PRIMARY KEY (id);


--
-- TOC entry 4750 (class 2606 OID 16422)
-- Name: schedules schedules_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT schedules_pkey PRIMARY KEY (id_schedule);


--
-- TOC entry 4762 (class 2606 OID 16514)
-- Name: service_activities service_activities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_activities
    ADD CONSTRAINT service_activities_pkey PRIMARY KEY (id);


--
-- TOC entry 4752 (class 2606 OID 16430)
-- Name: services services_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.services
    ADD CONSTRAINT services_pkey PRIMARY KEY (id);


--
-- TOC entry 4754 (class 2606 OID 16446)
-- Name: users uk_6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk_6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4744 (class 2606 OID 16442)
-- Name: clients uk_e3it7h0veoeergtkfqxhos5qj; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uk_e3it7h0veoeergtkfqxhos5qj UNIQUE (phone);


--
-- TOC entry 4768 (class 2606 OID 16592)
-- Name: orders_old_services uk_p97xke6xvhryjt0yav5b9bm7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_old_services
    ADD CONSTRAINT uk_p97xke6xvhryjt0yav5b9bm7 UNIQUE (services_id);


--
-- TOC entry 4746 (class 2606 OID 16440)
-- Name: clients uk_s0ydiqwgl7l9b8ripxjdvd2xb; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT uk_s0ydiqwgl7l9b8ripxjdvd2xb UNIQUE (document);


--
-- TOC entry 4756 (class 2606 OID 16438)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4758 (class 2606 OID 16492)
-- Name: warranties warranties_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT warranties_pkey PRIMARY KEY (id);


--
-- TOC entry 4779 (class 2606 OID 16618)
-- Name: service_activities fk5v9t74pjc3yis015cs4uvivna; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_activities
    ADD CONSTRAINT fk5v9t74pjc3yis015cs4uvivna FOREIGN KEY (order_id) REFERENCES public.orders_old(id);


--
-- TOC entry 4788 (class 2606 OID 16640)
-- Name: orders_services fkc48l84md8y5o0nub8vy8gxtec; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_services
    ADD CONSTRAINT fkc48l84md8y5o0nub8vy8gxtec FOREIGN KEY (orders_id) REFERENCES public.orders(id);


--
-- TOC entry 4780 (class 2606 OID 16520)
-- Name: service_activities fkd7mm6yf6f6yamr772t96amm0e; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_activities
    ADD CONSTRAINT fkd7mm6yf6f6yamr772t96amm0e FOREIGN KEY (technician_id) REFERENCES public.users(id);


--
-- TOC entry 4772 (class 2606 OID 16467)
-- Name: schedules fkdb7rash9ovdgr553udi1f7yb9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT fkdb7rash9ovdgr553udi1f7yb9 FOREIGN KEY (users_id) REFERENCES public.users(id);


--
-- TOC entry 4775 (class 2606 OID 16655)
-- Name: warranties fkehwlr8fog1vug2xovi2aigg0b; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT fkehwlr8fog1vug2xovi2aigg0b FOREIGN KEY (order_service_id) REFERENCES public.orders_services(id);


--
-- TOC entry 4773 (class 2606 OID 16613)
-- Name: schedules fkf2hw7iraxqljbl35n6236x4q9; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT fkf2hw7iraxqljbl35n6236x4q9 FOREIGN KEY (fk_orders) REFERENCES public.orders_old(id);


--
-- TOC entry 4777 (class 2606 OID 16556)
-- Name: evidences fkfdho7s6b3tunijp6gbj8hilid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evidences
    ADD CONSTRAINT fkfdho7s6b3tunijp6gbj8hilid FOREIGN KEY (order_service_id) REFERENCES public.order_services(id);


--
-- TOC entry 4781 (class 2606 OID 16515)
-- Name: service_activities fkg7565gjybow4da2mmi52fhgii; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_activities
    ADD CONSTRAINT fkg7565gjybow4da2mmi52fhgii FOREIGN KEY (order_id) REFERENCES public.orders(id);


--
-- TOC entry 4782 (class 2606 OID 16571)
-- Name: order_services fki3mq0o1uxe0j7jtexivv7la7k; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_services
    ADD CONSTRAINT fki3mq0o1uxe0j7jtexivv7la7k FOREIGN KEY (technician_id) REFERENCES public.users(id);


--
-- TOC entry 4776 (class 2606 OID 16576)
-- Name: warranties fki497xvty1m5jscqlh371iyjh0; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.warranties
    ADD CONSTRAINT fki497xvty1m5jscqlh371iyjh0 FOREIGN KEY (order_service_id) REFERENCES public.order_services(id);


--
-- TOC entry 4789 (class 2606 OID 16650)
-- Name: orders_services fkk9cs9uuu8py6sjsuj40tiggxk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_services
    ADD CONSTRAINT fkk9cs9uuu8py6sjsuj40tiggxk FOREIGN KEY (technician_id) REFERENCES public.users(id);


--
-- TOC entry 4785 (class 2606 OID 16598)
-- Name: orders_old fkkahxmxlge3sxl0pewk7o28q5o; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_old
    ADD CONSTRAINT fkkahxmxlge3sxl0pewk7o28q5o FOREIGN KEY (clients_id) REFERENCES public.clients(id);


--
-- TOC entry 4778 (class 2606 OID 16635)
-- Name: evidences fkkevwjdvafe24b7g2824eskxce; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evidences
    ADD CONSTRAINT fkkevwjdvafe24b7g2824eskxce FOREIGN KEY (order_service_id) REFERENCES public.orders_services(id);


--
-- TOC entry 4774 (class 2606 OID 16462)
-- Name: schedules fkmhp54pa6oavrg8knkgruk21t2; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schedules
    ADD CONSTRAINT fkmhp54pa6oavrg8knkgruk21t2 FOREIGN KEY (fk_orders) REFERENCES public.orders(id);


--
-- TOC entry 4786 (class 2606 OID 16603)
-- Name: orders_old_services fkrin81vb0is9yyvk2x8q3ek74g; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_old_services
    ADD CONSTRAINT fkrin81vb0is9yyvk2x8q3ek74g FOREIGN KEY (services_id) REFERENCES public.services(id);


--
-- TOC entry 4771 (class 2606 OID 16537)
-- Name: orders fkrxqv08hvs3v1b8cyog4y0yxgl; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fkrxqv08hvs3v1b8cyog4y0yxgl FOREIGN KEY (client_id) REFERENCES public.clients(id);


--
-- TOC entry 4783 (class 2606 OID 16561)
-- Name: order_services fkt0ada9cr6dkyroft0ueg4ddl8; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_services
    ADD CONSTRAINT fkt0ada9cr6dkyroft0ueg4ddl8 FOREIGN KEY (orders_id) REFERENCES public.orders(id);


--
-- TOC entry 4784 (class 2606 OID 16566)
-- Name: order_services fkt2255pq60ycps9n8hffiy8ulu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.order_services
    ADD CONSTRAINT fkt2255pq60ycps9n8hffiy8ulu FOREIGN KEY (services_id) REFERENCES public.services(id);


--
-- TOC entry 4790 (class 2606 OID 16645)
-- Name: orders_services fktf3befn48p2sqt2k9qbs1cso3; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_services
    ADD CONSTRAINT fktf3befn48p2sqt2k9qbs1cso3 FOREIGN KEY (services_id) REFERENCES public.services(id);


--
-- TOC entry 4787 (class 2606 OID 16608)
-- Name: orders_old_services fkwcptqo96u285d9sm5lk1o5na; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders_old_services
    ADD CONSTRAINT fkwcptqo96u285d9sm5lk1o5na FOREIGN KEY (orders_id) REFERENCES public.orders_old(id);


-- Completed on 2024-06-03 14:19:51

--
-- PostgreSQL database dump complete
--

